<a href="https://colab.research.google.com/github/yukinaga/minnano_kaggle/blob/main/section_3/04_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# アンサンブル学習
複数の機械学習モデルを組み合わせる、「アンサンブル学習」にトライしましょう。  
予測結果で多数決を行い、Kaggleに提出して結果を確認しましょう。

## データの準備
異なる機械学習モデルによる予測結果を読み込みます。  
これらを1つのデータフレームにまとめ、予測結果の相関関係を計算します。  
一部、CSVファイル名の変更が必要です。

In [7]:
import pandas as pd

subm_rf = pd.read_csv("submission_titanic_rf.csv")  #  section_2/02_titanic_random_forest.ipynb
subm_svc = pd.read_csv("submission_titanic_svc.csv")  #  section_2/03_exercise.ipynb
subm_lgbm = pd.read_csv("submission_titanic_cv.csv")  # section_3/03_cross_validation.ipynb

ensemble_df = pd.DataFrame({"subm_rf": subm_rf["Survived"].values,
                            "subm_svc": subm_svc["Survived"].values,
                            "subm_lgbm": subm_lgbm["Survived"].values})
ensemble_df.head()

   subm_rf  subm_svc  subm_lgbm
0        0         0          0
1        0         0          0
2        0         0          0
3        0         0          0
4        1         0          0

In [8]:
ensemble_df.corr()  # 各列の相関関係

            subm_rf  subm_svc  subm_lgbm
subm_rf    1.000000  0.240192   0.898717
subm_svc   0.240192  1.000000   0.222265
subm_lgbm  0.898717  0.222265   1.000000

## 多数決による生存/死亡の決定
複数の機械学習モデルによる予測結果で、多数決を行います。  
結果をCSVファイルに保存し、Kaggleに提出して結果を確認しましょう。

In [9]:
subm_data = subm_rf.copy()  # PassengerIdを転用

# 多数決で生存/死亡を決定
subm_data["Survived"] = subm_rf["Survived"] + subm_svc["Survived"] + subm_lgbm["Survived"]
subm_data["Survived"] = (subm_data["Survived"]>=2).astype(int)

subm_data.to_csv("submission_titanic_ensemble.csv", index=False)
subm_data.head()

   PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0